### ISSUE TITLE
Text Enhancement

### ISSUE THREAD

**Issue by andrestone** [Picovoice/speech-to-text-benchmark#10]
Hi!

I've tried Cheetah briefly in the past and I could only get capitalized letters and spaces for the transcription output. The cloud providers featured on this benchmark offer a transcription with punctuation and appropriate letter capitalization.

Is it still the case? If so, maybe add this information to the README?

Thanks.

**Comment by kenarsa** [comment]
Thank you @andrestone no we don't do punctuation and capitalisation, yet. but it is coming this year. the benchmark only goes through WER. other features are not compared here.
