### ISSUE TITLE
Consider adding whisper.cpp and faster-whisper to comparison

### ISSUE THREAD

**Issue by shvchk** [Picovoice/speech-to-text-benchmark#11]
Both run on CPU.

[whisper.cpp](https://github.com/ggerganov/whisper.cpp) is a port of Whisper in C++, it's now probably one of the most popular open-source speech-to-text models running offline on CPU. With the smallest `tiny` model (75 MB) it's 5-6 times slower than Leopard in my tests, though.

[faster-whisper](https://github.com/guillaumekln/faster-whisper) is a reimplementation of Whisper model using [CTranslate2](https://github.com/OpenNMT/CTranslate2/). It's not as popular yet, but it's 5 times faster than whisper.cpp on the same model, which makes it comparable to Leopard in terms of speed (even though it used 75 MB `tiny` model), in my tests.

**Comment by kenarsa** [comment]
@shvchk please feel free to submit a PR for any new engines you like. we are happy to look into them.
