### ISSUE TITLE
Compare against Mozilla DeepSpeech TFLite and update to current DeepSpeech?

### ISSUE THREAD

**Issue by danry25** [Picovoice/speech-to-text-benchmark#7]
Heads up, [Mozilla DeepSpeech v0.7.0](https://github.com/mozilla/DeepSpeech/releases/tag/v0.7.0) has been out for a bit with a word error rate of 5.97%.

There is also a Tensorflow Lite model weighing in at 45MB, not sure if this was overlooked earlier, but it has been around since [January 2019](https://github.com/mozilla/DeepSpeech/releases/tag/v0.4.1). This TFLite model is likely a better thing to compare Picovoice Leopard & Cheetah against if the focus is on low resource devices.

I hope your team is faring well in spite of this pandemic!

**Comment by kenarsa** [comment]
We update this repo with cheetah/leopard release cycles. the version of deepspeech used is depicted in the result table to avoid confusion. we will use the latest available in the time of the next release. it seems like the tflite models are available for download in 0.7 (and hopefully onward). this would be good useful addition (in older verson you had to export yourself).
