### ISSUE TITLE
DeepSpeech benchmark statistics are very outdated

### ISSUE THREAD

**Issue by Technerder** [Picovoice/speech-to-text-benchmark#8]
The statistics for Mozilla's DeepSpeech are outdated even compared to version 0.6 (Please see https://hacks.mozilla.org/2019/12/deepspeech-0-6-mozillas-speech-to-text-engine/)

**Comment by kenarsa** [comment]
I agree and we will update this when we release a new version of our engine. we have the version of DS used in the table to remove any confusion ...
